services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - default

  # Uncomment if not using cache
  # redis:
  #   container_name: redis
  #   image: redis:6-alpine
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - default
  #   restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - database
    networks:
      - default

networks:
  default:
